In [153]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import xml.etree.ElementTree as ET
import sklearn.metrics


In [154]:
train = pd.read_csv('hr_emp.csv')
train["Department"].unique()


array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [155]:
train1=train.drop(columns=['EmployeeCount','StandardHours','EmployeeNumber','Over18','Attrition'])
train1

Age     BusinessTravel  DailyRate              Department  \
0      41      Travel_Rarely       1102                   Sales   
1      49  Travel_Frequently        279  Research & Development   
2      37      Travel_Rarely       1373  Research & Development   
3      33  Travel_Frequently       1392  Research & Development   
4      27      Travel_Rarely        591  Research & Development   
...   ...                ...        ...                     ...   
1465   36  Travel_Frequently        884  Research & Development   
1466   39      Travel_Rarely        613  Research & Development   
1467   27      Travel_Rarely        155  Research & Development   
1468   49  Travel_Frequently       1023                   Sales   
1469   34      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EnvironmentSatisfaction  \
0                    1          2  Life Sciences                        2   
1                    8          1  Life Sciences                        3   
2                    2          2          Other                        4   
3                    3          4  Life Sciences                        4   
4                    2          1        Medical                        1   
...                ...        ...            ...                      ...   
1465                23          2        Medical                        3   
1466                 6          1        Medical                        4   
1467                 4          3  Life Sciences                        2   
1468                 2          3        Medical                        4   
1469                 8          3        Medical                        2   

      Gender  HourlyRate  ...  PerformanceRating  RelationshipSatisfaction  \
0     Female          94  ...                  3                         1   
1       Male          61  ...                  4                         4   
2       Male          92  ...                  3                         2   
3     Female          56  ...                  3                         3   
4       Male          40  ...                  3                         4   
...      ...         ...  ...                ...                       ...   
1465    Male          41  ...                  3                         3   
1466    Male          42  ...                  3                         1   
1467    Male          87  ...                  4                         2   
1468    Male          63  ...                  3                         4   
1469    Male          82  ...                  3                         1   

     StockOptionLevel  TotalWorkingYears TrainingTimesLastYear  \
0                   0                  8                     0   
1                   1                 10                     3   
2                   0                  7                     3   
3                   0                  8                     3   
4                   1                  6                     3   
...               ...                ...                   ...   
1465                1                 17                     3   
1466                1                  9                     5   
1467                1                  6                     0   
1468                0                 17                     3   
1469                0                  6                     3   

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                   1               6                   4   
1                   3              10                   7   
2                   3               0                   0   
3                   3               8                   7   
4                   3               2                   2   
...               ...             ...                 ...   
1465                3               5                   2   
1466                3               7                   7 

In [161]:
from sklearn.model_selection import train_test_split
train_df,test_df = train_test_split(train1, test_size=0.20, random_state=80)



In [162]:


print('Total duplicate Values in the train dataset = ',train.duplicated())
print('Total missing values in train dataset = ',train.isnull().sum())

Total duplicate Values in the train dataset =  0       False
1       False
2       False
3       False
4       False
        ...  
1465    False
1466    False
1467    False
1468    False
1469    False
Length: 1470, dtype: bool
Total missing values in train dataset =  Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceR

In [163]:
qualitative =  [f for f  in train_df.columns if train.dtypes[f] == 'object']

qualitative

['BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'OverTime']

In [164]:
for i in qualitative :
    
    train_df[i] = pd.Categorical(train_df[i])
    print(i,train_df[i].unique(),train_df[i].head(5))
    train_df[i] = pd.factorize(train_df[i])[0]
    print(i,train_df[i].unique(),train_df[i].head(5))
#train_df=pd.get_dummies(data=train_df,columns=qualitative)




BusinessTravel ['Travel_Rarely', 'Travel_Frequently', 'Non-Travel']
Categories (3, object): ['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'] 1342        Travel_Rarely
959         Travel_Rarely
1217        Travel_Rarely
814         Travel_Rarely
1056    Travel_Frequently
Name: BusinessTravel, dtype: category
Categories (3, object): ['Non-Travel', 'Travel_Frequently', 'Travel_Rarely']
BusinessTravel [0 1 2] 1342    0
959     0
1217    0
814     0
1056    1
Name: BusinessTravel, dtype: int64
Department ['Sales', 'Research & Development', 'Human Resources']
Categories (3, object): ['Sales', 'Research & Development', 'Human Resources'] 1342                     Sales
959     Research & Development
1217    Research & Development
814     Research & Development
1056                     Sales
Name: Department, dtype: category
Categories (3, object): ['Human Resources', 'Research & Development', 'Sales']
Department [0 1 2] 1342    0
959     1
1217    1
814     1
1056    0
Name: Department, dt

<ipython-input-164-89145cfc119e>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[i] = pd.Categorical(train_df[i])
<ipython-input-164-89145cfc119e>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[i] = pd.factorize(train_df[i])[0]


In [8]:
for i in qualitative :
    
    test_df[i] = pd.Categorical(test_df[i])
    test_df[i] = pd.factorize(test_df[i])[0]

<ipython-input-8-32ad6419c083>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[i] = pd.Categorical(test_df[i])
<ipython-input-8-32ad6419c083>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[i] = pd.factorize(test_df[i])[0]


In [9]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 294 entries, 872 to 651
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       294 non-null    int64
 1   BusinessTravel            294 non-null    int64
 2   DailyRate                 294 non-null    int64
 3   Department                294 non-null    int64
 4   DistanceFromHome          294 non-null    int64
 5   Education                 294 non-null    int64
 6   EducationField            294 non-null    int64
 7   EnvironmentSatisfaction   294 non-null    int64
 8   Gender                    294 non-null    int64
 9   HourlyRate                294 non-null    int64
 10  JobInvolvement            294 non-null    int64
 11  JobLevel                  294 non-null    int64
 12  JobRole                   294 non-null    int64
 13  JobSatisfaction           294 non-null    int64
 14  MaritalStatus             294 non-null  

In [10]:
X_train = train_df.drop(columns=[ 'Department'])
y_train = train_df['Department']


In [138]:
print (train['JobRole'].unique())

['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']


In [12]:
X_test = train_df.drop(columns=[ 'Department'])
y_test = train_df['Department']
print(len(X_test))

1176


In [104]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2 , f_regression

KBest = SelectKBest(score_func = f_regression, k = 6)
print(KBest)
KBest = KBest.fit(X_train,y_train)

df_scores = pd.DataFrame({'features': X_train.columns, 'f_regression': KBest.scores_ })
df_scores1=df_scores.sort_values(by='f_regression', ascending=False)
df_scores1

SelectKBest(k=6, score_func=<function f_regression at 0x000001ABAE0373A0>)


features  f_regression
11                   JobRole    472.649660
5             EducationField     43.637409
10                  JobLevel     10.181539
0                        Age      2.859237
14             MonthlyIncome      2.632919
26        YearsInCurrentRole      2.603758
16        NumCompaniesWorked      2.447703
9             JobInvolvement      1.795690
6    EnvironmentSatisfaction      1.578000
27   YearsSinceLastPromotion      1.133716
3           DistanceFromHome      1.084766
23     TrainingTimesLastYear      0.988755
24           WorkLifeBalance      0.742288
19         PerformanceRating      0.720499
7                     Gender      0.667888
22         TotalWorkingYears      0.617203
15               MonthlyRate      0.599417
18         PercentSalaryHike      0.317162
2                  DailyRate      0.244855
28      YearsWithCurrManager      0.184565
4                  Education      0.170982
17                  OverTime      0.156883
12           JobSatisfaction      0.130814
20  RelationshipSatisfaction      0.078731
1             BusinessTravel      0.063673
8                 HourlyRate      0.058242
25            YearsAtCompany      0.024982
13             MaritalStatus      0.019412
21          StockOptionLevel      0.006438

In [127]:
df_scores2=df_scores1[:6]
selected_features=df_scores2['features']
df_scores2

features  f_regression
11             JobRole    472.649660
5       EducationField     43.637409
10            JobLevel     10.181539
0                  Age      2.859237
14       MonthlyIncome      2.632919
26  YearsInCurrentRole      2.603758

In [128]:
cols = KBest.get_support(indices=True)
features = X_train.columns[cols]
list(features)

['Age',
 'EducationField',
 'JobLevel',
 'JobRole',
 'MonthlyIncome',
 'YearsInCurrentRole']

In [129]:
final_train = X_train[selected_features]

final_test=X_test[selected_features]

In [130]:
#from sklearn.linear_model import LogisticRegression
#log_model = LogisticRegression(multi_class="multinomial")
#from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
#i=0

   
#log_model.fit(final_train ,y_train)

In [131]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
#X, y = make_classification(n_samples=1000, n_features=4,n_informative=2, n_redundant=0,random_state=0, shuffle=False)
clf = RandomForestClassifier(max_depth=6)
#CV_rfc = GridSearchCV(estimator=rfc,cv= 10, scoring = 'roc_auc')
clf.fit(final_train ,y_train)
print(clf.predict_proba(final_test))

[[0.9282939  0.06822597 0.00348013]
 [0.05353393 0.93314856 0.01331751]
 [0.03138925 0.95813578 0.01047498]
 ...
 [0.06366374 0.92896623 0.00737003]
 [0.05394212 0.93666871 0.00938917]
 [0.04809035 0.939247   0.01266265]]


In [132]:
from sklearn.metrics import confusion_matrix,classification_report,plot_confusion_matrix
from sklearn import metrics
predictions = clf.predict(final_test)

#print(y_test.head(10))
#print(predictions[6])
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
#type(final_test)
print("accuracy: {:0.3f}".format(metrics.accuracy_score(y_test,predictions)))


[[295  52   0]
 [  0 776   0]
 [  0   5  48]]
              precision    recall  f1-score   support

           0       1.00      0.85      0.92       347
           1       0.93      1.00      0.96       776
           2       1.00      0.91      0.95        53

    accuracy                           0.95      1176
   macro avg       0.98      0.92      0.94      1176
weighted avg       0.95      0.95      0.95      1176

accuracy: 0.952


In [133]:
from sklearn.metrics import confusion_matrix,classification_report,plot_confusion_matrix
x=[53,13,2,0,1,1]
x=pd.DataFrame(x)

x=x.transpose()
#print(x)
#y=x.reshape(-1, 1)
check=clf.predict_proba(x)
print(check)

[[0.13258065 0.14245161 0.72496774]]


In [134]:
#import matplotlib.pyplot as plt
#from sklearn.datasets import make_classification
#from sklearn.metrics import plot_confusion_matrix
#from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

#X, y = make_classification(random_state=0)
#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
#clf = SVC(random_state=0)
#clf.fit(X_train, y_train)
#SVC(random_state=0)
#plot_confusion_matrix(X_test, y_test)  
#plt.show()

In [135]:
 import pickle

In [136]:
with open(r'F:\model_sav', 'wb') as f:
    pickle.dump(clf, f)